### PR TITLE
Update Package.swift

### PR DESCRIPTION
**Pull request by Juice805**
Due to current structure much of it has to be specified manually, but this adds Swift Package Manager support for the library + Swift tests

### CODE REVIEW

**Comment by Juice805** [comment]
If anyone needs this with SwiftPM it is available on [my fork](https://github.com/Juice805/SwiftHTTPStatusCodes) until merged. It is tagged as version 3.2.1.

**Comment by rhodgkins** [comment]
Sorry I've only just managed to get around to this @Juice805 - appreciate the work.

Also does this resolve #11?

**Comment by rhodgkins** [comment]
@Juice805 - any chance you know if this will resolve #11?

**Comment by Juice805** [comment]
It should fix that error, yes.

**Comment by rhodgkins** [comment]
@Juice805 would it be possible for you to update this for Swift 5? (Don't worry if not, I can probably work it out!)

**Pull request closed without merging**
